### ISSUE TITLE
PIC16F15244 SPI demo examples request

### ISSUE THREAD

**Issue by fxj000** [microchip-pic-avr-examples/pic16f15244-family-simple-i2c-io-expander#1]
hi, @robertperkel 
You did a great job and all examples very easy to use!
Could you please share a SPI example for us, thank you so much. :)
if need, this is my email: fxj460@163.com

**Comment by pic-avr-github-admin** [comment]
Hi @fxj000 ,
I released a bare metal SPI driver for the PIC16F15244: https://github.com/microchip-pic-avr-examples/pic16f15244-bare-metal-spi-mplab
The apps team also developed a SPI I/O expander example for the PIC16F15276 (larger pin count device) using the MCC libraries: 
https://github.com/microchip-pic-avr-examples/pic16f15276-cnano-spi-io-expander-client-mplab-mcc
https://github.com/microchip-pic-avr-examples/pic16f15276-cnano-spi-io-expander-host-mplab-mcc
